### ISSUE TITLE
Organisation de l'histoire

### ISSUE THREAD

**Issue by dylan-marsangy** [PolytechLyon/git-5a-g2-grandjean-marsangy-marguet-philibert#1]
Fichier créé avec le début de l'intrigue. A votre tour !

**Comment by dylan-marsangy** [comment]
@M-Garrigues Ton fichier histoire devrait être supprimé et son contenu (pour l'instant vide) déplacé dans le README.

**Comment by M-Garrigues** [comment]
C'est fait sur le master, normalement

**Comment by M-Garrigues** [comment]
Nevermind, je corrige ça

**Comment by lauraphilibert** [comment]
Mathieu, ta branche n'est pas mergée sur master

**Comment by Maganik** [comment]
Attendez mais c'est pas le livreur qui se perd ?

**Comment by dylan-marsangy** [comment]
Toutes les parties sont là ?

Il manque pas celle qui explique comment le livreur est mort ?

**Comment by dylan-marsangy** [comment]
@M-Garrigues C'était pas la tienne du coup ?

**Comment by Maganik** [comment]
Je crois qu'il manque la partie du livreur qui se perd

**Comment by lauraphilibert** [comment]
Les 2 oui

**Comment by lauraphilibert** [comment]
@M-Garrigues au risque de me répéter, ta branche n'a pas été mergée sur master si je ne m'abuse

**Comment by M-Garrigues** [comment]
Désolé la mort du livreur arrive, me suis gourré
