### ISSUE TITLE
Jean Eude adventures v2

### ISSUE THREAD

**Issue by Maganik** [PolytechLyon/git-5a-g2-grandjean-marsangy-marguet-philibert#11]

**Comment by dylan-marsangy** [comment]
J'ai créé le fichier.

**Comment by M-Garrigues** [comment]
- [ ] Introduction

- [ ] Rentre dans l'usine et tombe sur la banane

- [ ]  Décède

- [ ] Se décompose..?

- [ ] Conclusion

**Comment by M-Garrigues** [comment]
C'est bien ça?

**Comment by dylan-marsangy** [comment]
Ok

**Comment by lauraphilibert** [comment]
Souci avec le .txt : les modifs ne se prennent pas toujours bien j'ai créé un . md à la place !!
