### ISSUE TITLE
Nouveau besoin : 4eme de couverture

### ISSUE THREAD

**Issue by dylan-marsangy** [PolytechLyon/git-5a-g2-grandjean-marsangy-marguet-philibert#4]
Dans un fichier à part...

Répartitions des tâches ?

**Comment by lauraphilibert** [comment]
qui crée le fichier?

**Comment by dylan-marsangy** [comment]
Je le fais

**Comment by lauraphilibert** [comment]
Je fais la partie inspecteur sur la 4ème de couv

**Comment by dylan-marsangy** [comment]
Je fais la partie introduction de Jean-Eude

**Comment by M-Garrigues** [comment]
Vous voulez mettre quoi exactement? Parce qu'un résumé de ça ça va être sacrément court quand même

**Comment by M-Garrigues** [comment]
D'autant que je vais pas mettre la partie de la mort de Jean-Eude, ce serait un terrible spoiler...

**Comment by lauraphilibert** [comment]
J'ai mis une petite phrase type : l'inspecteur va vivre de folles aventures sans préciser le contexte.

**Comment by dylan-marsangy** [comment]
C'est vrai. Je considère la 4ème de couverture fini. Rouvrez l'issue si vous n'êtes pas ok.
